// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0tKUaiTUdYdzDJjiXvWzw4J_jAXEta-4',
    appId: '1:744752433120:web:085e508f17140a3f8a0d85',
    messagingSenderId: '744752433120',
    projectId: 'wit-space',
    authDomain: 'wit-space.firebaseapp.com',
    storageBucket: 'wit-space.firebasestorage.app',
    measurementId: 'G-NNK36B7YFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnQSWlslCk_WU3PvutFugGIek5bDPnkIA',
    appId: '1:744752433120:android:68778503844e41418a0d85',
    messagingSenderId: '744752433120',
    projectId: 'wit-space',
    storageBucket: 'wit-space.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuT77X8gt_vzNQ3n-7Rf6Gykz46ZX9oJU',
    appId: '1:744752433120:ios:4e393f9bcbc285958a0d85',
    messagingSenderId: '744752433120',
    projectId: 'wit-space',
    storageBucket: 'wit-space.firebasestorage.app',
    iosBundleId: 'com.example.projectWitspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuT77X8gt_vzNQ3n-7Rf6Gykz46ZX9oJU',
    appId: '1:744752433120:ios:4e393f9bcbc285958a0d85',
    messagingSenderId: '744752433120',
    projectId: 'wit-space',
    storageBucket: 'wit-space.firebasestorage.app',
    iosBundleId: 'com.example.projectWitspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0tKUaiTUdYdzDJjiXvWzw4J_jAXEta-4',
    appId: '1:744752433120:web:b8d6b7190a301d7b8a0d85',
    messagingSenderId: '744752433120',
    projectId: 'wit-space',
    authDomain: 'wit-space.firebaseapp.com',
    storageBucket: 'wit-space.firebasestorage.app',
    measurementId: 'G-5MV3NT9L8F',
  );
}
